title: Indian Women Safety


theme: minima
minima:
  skin: dark  # or 'auto' to match system preference

# Remote theme for latest dark support (optional)
remote_theme: jekyll/minima
# plugins:
#   - jekyll-remote-theme
